### ISSUE TITLE
Invalid decomp project

### ISSUE THREAD

**Issue by MatHDDH** [z64a/star-rod#10]
Whenever I boot up star rod, it tells me to select a project file and when I do it says that it's missing the us version of the game. I tried dumping the game and selecting that as the project folder, but it keeps sending the same message.

**Comment by bates64** [comment]
Have you cloned https://github.com/pmret/papermario or https://github.com/bates64/papermario-dx and placed the baserom in `ver/us/baserom.z64`?

**Comment by MatHDDH** [comment]
where do I place the ver folder?

**Comment by bates64** [comment]
There is already a ver directory inside the papermario or papermario-dx directory.
See https://docs.starhaven.dev/tools/decomp/setup.html for detailed instructions

**Comment by MatHDDH** [comment]
will do, thanks!
