### ISSUE TITLE
US version not found.

### ISSUE THREAD

**Issue by Sanic24** [z64a/star-rod#7]
The 0.5.3 version works perfectlly, but this version says its not a us version.

**Comment by z64a** [comment]
This version requires a decomp or dx project based on the US version to operate on.

**Comment by MatHDDH** [comment]
It still doesn't work even with a proper game dump

**Comment by srt-jay** [comment]
No explanation of how to set it up from a downloaded release, obviously it is missing files and/or documentation.

Same issue. Version 0.5.3 works perfectly fine. Unless the newest version has ground-breaking features, in which case if somebody could share here how to fix the issue, that would be great. Already have the decomp downloaded, where does it go? What should the folder name be, as in, what is the software expecting?

Documentation should be on here or a wiki or something that is available through traditional channels.

In the older version, a folder called "dump" was expected IIRC for the original decomp. This does not work in 0.10.2 and the error provides absolutely no useful information in fixing the problem. Tried renaming 'dump' to 'src.' Nothing. What is needed to fix this error?
